Controllers/DiseasesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Capstone1.Models;
using Microsoft.AspNet.Identity;

namespace Capstone1.Controllers
{
    public class DiseasesController : Controller
    {
        private CapstoneEntities1 db = new CapstoneEntities1();
        //[Authorize(Roles ="Admin")]
        // GET: Diseases
        public ActionResult Index()
        {
            return View(db.Diseases.ToList());
        }

        // GET: Diseases/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Disease disease = db.Diseases.Find(id);
            if (disease == null)
            {
                return HttpNotFound();
            }
            return View(disease);
        }
        [Authorize(Roles = "Admin")]
        // GET: Diseases/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Diseases/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DiseaseName,Description")] Disease disease)
        {
            if (ModelState.IsValid)
            {
                db.Diseases.Add(disease);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(disease);
        }
        [Authorize(Roles = "Admin")]
        // GET: Diseases/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Disease disease = db.Diseases.Find(id);
            if (disease == null)
            {
                return HttpNotFound();
            }
            return View(disease);
        }

        // POST: Diseases/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DiseaseName,Description")] Disease disease)
        {
            if (ModelState.IsValid)
            {
                db.Entry(disease).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(disease);
        }
        [Authorize(Roles = "Admin")]
        // GET: Diseases/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Disease disease = db.Diseases.Find(id);
            if (disease == null)
            {
                return HttpNotFound();
            }
            return View(disease);
        }

        // POST: Diseases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Disease disease = db.Diseases.Find(id);
            db.Diseases.Remove(disease);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult LinkSymptoms()
        {

            ViewBag.AllSymptoms = new MultiSelectList(db.Symptoms.ToList(), "Id", "SymptomName");
            return View();
        }
        [HttpPost]
        public ActionResult ShowDiseasesBySymptoms(SymptomListViewModel model)
        {
            var UserId = User.Identity.GetUserId();
            var Profile = db.UserProfiles.Single(U => U.UserId == UserId);
            
            var MatchingDiseases = new List<Disease>();
            if (ModelState.IsValid && model != null && model.SymptomIds != null)
            {
                

                foreach (var Disease in db.Diseases)
                {
                    var MatchingSymptoms = Disease.Symptoms.Join(model.SymptomIds, s => s.Id, x => x, (l, r) => l);
                    var SymptomCount = MatchingSymptoms.Count();
                    if (SymptomCount >=3)
                    {
                        MatchingDiseases.Add(Disease);
                    }
                }
                

                

            }

            return View(MatchingDiseases);
            
        }
        [Authorize (Roles = "Admin")]
        public ActionResult EditSymptoms(int? id)
        {
            var Disease = db.Diseases.Find(id);
            var ExistingSymptoms = Disease.Symptoms.Select(d => d.Id).ToList();
            ViewBag.AllSymptoms = new MultiSelectList(db.Symptoms.ToList(), "Id", "SymptomName", ExistingSymptoms);
            return View();
        }
        [HttpPost]
        public ActionResult EditSymptoms(int? id, SymptomListViewModel model)
        {

            var Disease = db.Diseases.Find(id);

            if (ModelState.IsValid)
            {
                

                Disease.Symptoms.Clear();
                if (model?.SymptomIds != null)
                {
                    foreach (var SymptomId in model.SymptomIds)
                    {
                        var Symptom = db.Symptoms.Find(SymptomId);
                        Disease.Symptoms.Add(Symptom);

                    }
                }

                db.Entry(Disease).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new {id = id});

            }

            
            var ExistingSymptoms = Disease.Symptoms.Select(d => d.Id).ToList();
            ViewBag.AllSymptoms = new MultiSelectList(db.Symptoms.ToList(), "Id", "SymptomName", ExistingSymptoms);
            return View(model);
        }


        //public ActionResult LinkDoctors()
        //{
        //    var UserId = User.Identity.GetUserId();
        //    var Profile = db.UserProfiles.Single(U => U.UserId == UserId);
        //    List<int> ExistingDoctors = Profile.Diseases.Select(d => d.Id).ToList();
        //    ViewBag.AllDoctors = new MultiSelectList(db.DoctorTypes.ToList(), "Id", "DoctorTypes", ExistingDoctors);
        //    return View();
        //}
        //[HttpPost]
        //public ActionResult LinkDoctors(AddDiseaseViewModel model)
        //{
        //    var UserId = User.Identity.GetUserId();
        //    var Profile = db.UserProfiles.Single(U => U.UserId == UserId);

        //    if (ModelState.IsValid)
        //    {
        //        Doctor.DoctorType.Clear();
        //        if (model?.DoctorIds != null)
        //        {
        //            foreach (var DiseaseId in model.DiseaseIds)
        //            {
        //                var Doctor = db.DoctorType.Find(DoctorId);
        //                DoctorType.Doctors.Add(Doctor);

        //            }
        //        }

        //        db.Entry(Profile).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");

        //    }

        //    var ExistingDoctors = Profile.Doctors.ToList();
        //    ViewBag.AllDoctors = new MultiSelectList(db.Doctors.ToList(), "Id", "DoctorType", ExistingDoctors);
        //    return View(model);
        //}
    }
}

Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <title>My Capstone Project</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <noscript><link href="~/Content/noscript.css" rel="stylesheet" /></noscript>
    
</head>
<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper">

        <!-- Header -->
        <header id="header">
            <a href="index.html" class="logo">Know They Self</a>
        </header>

        <!-- Nav -->
        <div>
            <nav id="nav">
                <ul class="links">
                    <li>@Html.ActionLink("Profile", "Index", "UserProfiles")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Disease Info", "Index", "Diseases")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </nav>
        </div>
        <!-- Main -->
        <div id="main">

            <!-- Post -->
            <section class="post">
                <header class="major">
                </header>
                @RenderBody()
            </section>

        </div>

        <!-- Footer -->
        <footer id="footer">
            <section>
                <form method="post" action="#">
                    <div class="fields">
                        <div class="field">
                            <label for="name">Name</label>
                            <input type="text" name="name" id="name" />
                        </div>
                        <div class="field">
                            <label for="email">Email</label>
                            <input type="text" name="email" id="email" />
                        </div>
                        <div class="field">
                            <label for="message">Message</label>
                            <textarea name="message" id="message" rows="3"></textarea>
                        </div>
                    </div>
                    <ul class="actions">
                        <li><input type="submit" value="Send Message" /></li>
                    </ul>
                </form>
            </section>
            <section class="split contact">
                <section class="alt">
                    <h3>Address</h3>
                    <p>
                        1234 Somewhere Road #87257<br />
                        Charlotte, NC 00000-0000
                    </p>
                </section>
                <section>
                    <h3>Phone</h3>
                    <p><a href="#">(614) 441-1028</a></p>
                </section>
                <section>
                    <h3>Email</h3>
                    <p><a href="#">lnrox@outlook.com</a></p>
                </section>
                <section>
                    <h3>Social</h3>
                    <ul class="icons alt">
                        <li><a href="#" class="icon brands alt fa-twitter"><span class="label">Twitter</span></a></li>
                        <li><a href="#" class="icon brands alt fa-facebook-f"><span class="label">Facebook</span></a></li>
                        <li><a href="#" class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>
                        <li><a href="#" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>
                    </ul>
                </section>
            </section>
        </footer>

        <!-- Copyright -->
        <div id="copyright">
            <ul><li>&copy; Untitled</li><li>Design: <a href="#">HTML5 UP</a></li></ul>
        </div>

    </div>

    <!-- Scripts -->

    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/jquery.scrollex.min.js"></script>
    <script src="~/Scripts/jquery.scrolly.min.js"></script>
    <script src="~/Scripts/browser.min.js"></script>
    <script src="~/Scripts/breakpoints.min.js"></script>
    <script src="~/Scripts/util.js"></script>
    <script src="~/Scripts/main.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>